### ISSUE TITLE
Package.json causing issues with Webpack v5

### ISSUE THREAD

**Issue by jcvandan** [alexanderschau/react-ionicons#8]
Hi! I'm running into an issue as I try to upgrade to webpack v5 from v4.

I keep getting an error related to the `@reacticons/iconicons` package. The error is:

```
Module not found: Error: Package path . is not exported from package
```

I have been having a dig and I can see that in your package.json you are defining both `main` and `exports` to let consumers know where to do the root level imports from. I had a look at the npm docs and it states the following about `exports`:

> It is supported in Node.js 12+ as an alternative to the "main" that can support defining subpath exports

If I modify the package.json directly in my node_modules folder and remove the `exports` property, my project builds fine. Is there a specific reason you added the `exports` along with the `main` property as it seems like only `main` is needed and webpack doesn't like both being defined.

Thanks!

**Comment by alexanderschau** [comment]
I added `exports` to reach the full package score [at skypack](https://www.skypack.dev/view/@reacticons/ionicons) (for [Deno](https://deno.land)). However if it causes an error, I will remove the `exports` property (at least for now).

Should be fixed with [version 6.0.3](https://www.npmjs.com/package/@reacticons/ionicons/v/6.0.3)
